
server:
  error:
    include-message: always
    include-binding-errors: always
    
spring:
  datasource:
    password: 26102001
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/libControl
    username: root
  jpa:
    hibernate:
      dialect:  org.hibernate.dialect.MySQLInnoDBDialect
      show-sql: true
      ddl-auto: update
      format-sqp: true
    properties:
      hibernate:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
        